version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
      - ./backend/public:/var/www/public
  composer:
    image: composer:latest
    volumes:
      - ./backend/composer.json:/var/www/composer.json
      - ./backend/composer.lock:/var/www/composer.lock
    container_name: composer
    working_dir: /var/www
    command: install
  php:
    image: php:fpm-alpine
    container_name: php
    working_dir: /var/www
    restart: always
    env_file: ./backend/.env
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./backend/public:/var/www/public
      - ./backend/src:/var/www/src
      - ./backend/vendor:/var/www/vendor
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
