version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
      - ./public:/var/www/public
    depends_on:
      - composer
      - php
  composer:
    image: composer:latest
    volumes:
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
    container_name: composer
    working_dir: /var/www
    command: install
  php:
    image: php:fpm-alpine
    container_name: php
    working_dir: /var/www
    restart: always
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./public:/var/www/public
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
